export enum ModalType {
	DELETE_EMPLOYEE = "DELETE_EMPLOYEE",
	DELETE_PROJECT = "DELETE_PROJECT",
	DELETE_PROJECT_DAY = "DELETE_PROJECT_DAY",
	ERROR = "ERROR",
	EXIT = "EXIT",
	RELOAD = "RELOAD",
	ROUTE = "ROUTE",
}
